### PR TITLE
Issue/3020

### LINKED ISSUE #3020: _edd_log_price_id incorrectly being set to 0, causing exports to fail
Export Customers in CSV is not working. Only exporting emails for all downloads is working.

### PR DESCRIPTION
**Pull request by pippinsplugins**
Fixes #3020

### CODE REVIEW

File: includes/admin/upgrades/upgrade-functions.php [hunk 1]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+			'posts_per_page' => -1
+		);
+
+		$sql = "SELECT ID FROM $wpdb->posts p LEFT JOIN $wpdb->postmeta m ON p.ID = m.post_id WHERE m.meta_key = '_variable_pricing' AND m.meta_value = 1";
+		$has_variable = $wpdb->get_col( $sql );
+
+		if( empty( $has_variable ) ) {
+			// We had no variable priced products, so go ahead and just complete
+			update_option( 'edd_version', preg_replace( '/[^0-9.].*/', '', EDD_VERSION ) );
+
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: Don't we need to run `delete_option( 'edd_doing_upgrade' );` here?

File: includes/admin/upgrades/upgrade-functions.php [hunk 2]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+	if ( 1 === $step ) {
+		// Check if we have any variable price products on the first step
+		$args = array(
+			'post_type'  => 'download',
+			'meta_key'   => '_variable_pricing',
+			'meta_value' => '1',
+			'posts_per_page' => -1
+		);
+
+		$sql = "SELECT ID FROM $wpdb->posts p LEFT JOIN $wpdb->postmeta m ON p.ID = m.post_id WHERE m.meta_key = '_variable_pricing' AND m.meta_value = 1";
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: This should have a `LIMIT` of `1` to ensure it's as fast as possible, yes?

File: includes/admin/upgrades/upgrade-functions.php [hunk 3]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+			$mapped_logs = array();
+
+			// Go through each cart download
+			foreach( $variable_downloads as $download ) {
+
+				// Itterate through the logs we found attached to this payment
+				foreach ( $logs as $key => $log ) {
+
+					// If this Log ID is associated with this download ID give it the price_id
+					if ( $log['download_id'] === $download['id'] ) {
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: Let's typecast these with `(int)` to be completely sure we don't miss any.

File: includes/admin/upgrades/upgrade-functions.php (hunk 1 above)
Comment (cklosowski) [inline includes/admin/upgrades/upgrade-functions.php]: :+1:

File: includes/admin/upgrades/upgrade-functions.php [hunk 4]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+
+			$variable_download_ids = array_unique( wp_list_pluck( $variable_downloads, 'id' ) );
+			$unique_download_ids   = implode( ',', $variable_download_ids );
+			// Get all Log Ids where the post parent is in the set of download IDs we found in the cart meta
+			$logs = $wpdb->get_results( "SELECT m.post_id AS log_id, p.post_parent AS download_id FROM $wpdb->postmeta m LEFT JOIN $wpdb->posts p ON m.post_id = p.ID WHERE meta_key = '_edd_log_payment_id' AND meta_value = $payment_id AND p.post_parent IN ($unique_download_ids)", ARRAY_A );
+
+			$mapped_logs = array();
+
+			// Go through each cart download
+			foreach( $variable_downloads as $download ) {
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: Let's change `$download` to something else so that we don't confuse ourselves with the loop above that also uses `$download`.

File: includes/admin/upgrades/upgrade-functions.php (hunk 2 above)
Comment (cklosowski) [inline includes/admin/upgrades/upgrade-functions.php]: Yes the original thought was to use the download IDs found. But that logic was later ditched.

File: includes/admin/upgrades/upgrade-functions.php [hunk 5]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+				foreach ( $logs as $key => $log ) {
+
+					// If this Log ID is associated with this download ID give it the price_id
+					if ( $log['download_id'] === $download['id'] ) {
+						$mapped_logs[$log['log_id']] = $download['price_id'];
+
+						// Remove this Download/Log ID from the list, for multipurchase compatibility
+						unset( $logs[$key] );
+
+						// These aren't the logs we're looking for. Move Along, Move Along.
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: +1 :beer:

File: includes/admin/upgrades/upgrade-functions.php (hunk 3 above)
Comment (cklosowski) [inline includes/admin/upgrades/upgrade-functions.php]: :+1:

File: includes/admin/upgrades/upgrade-functions.php [hunk 6]
```diff
@@ -556,9 +600,140 @@ function edd_v21_upgrade_customers_db() {
...
+		$redirect = add_query_arg( array(
+			'page'        => 'edd-upgrades',
+			'edd-upgrade' => 'upgrade_payments_db',
+			'step'        => $step
+		), admin_url( 'index.php' ) );
+		wp_redirect( $redirect ); exit;
+
+	} else {
+
+		// No more customers found, finish up
```
Comment (pippinsplugins) [inline includes/admin/upgrades/upgrade-functions.php]: payments, not customers
