### PR TITLE
fix `hide_on_checkout` bug in `edd_cart_widget`

### LINKED ISSUE #4199: Cart Widget doesn't show on checkout page when configured to do so
Customer reported and confirmed locally.

`$instance['hide_on_checkout']` is always set [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/widgets.php#L44), it's just empty.

### PR DESCRIPTION
**Pull request by felixarntz**
fixes #4199

### CODE REVIEW

File: includes/widgets.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ function __construct() {
 	/** @see WP_Widget::widget */
 	function widget( $args, $instance ) {
 
-		if ( isset( $instance['hide_on_checkout'] ) && edd_is_checkout() ) {
+		if ( isset( $instance['hide_on_checkout'] ) && $instance['hide_on_checkout'] && edd_is_checkout() ) {
```
Comment (pippinsplugins) [inline includes/widgets.php]: This could be simplified to just `if ( ! empty( $instance['hide_on_checkout'] ) `

**Comment by cklosowski** [comment]
Thanks @felixarntz
