### PR TITLE
Show success message after manually creating order #8191

### LINKED ISSUE #8191: 3.0 - No success message after manually creating order
### Expected behavior

After saving a new manually-created order, I expect to see a success message.

### Actual behavior

You get taken to the `view-order-details` page, but no success message is shown. It doesn't make it super clear that the order was in fact created.

### Steps to reproduce the behavior
1) Go to Downloads > Orders > Add New and create a new order.
2) After saving, you will be on the `view-order-details` page for the new order, but there's no success message visible.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by ashleyfae**
Fixes #8191

Proposed Changes:
1. Move all order related notices out of the "Shop reports errors" section and into the order-related notices. I think they were just in the wrong spot.
2. Create a new notice for `order_added` and include this notice in the page redirect after making an order.
3. Correct return type in PHPDocs for `edd_add_manual_order()`.

To test:

Manually create a new order and ensure you get a success message after doing so.

### CODE REVIEW

File: includes/admin/class-edd-notices.php [hunk 1]
```diff
@@ -610,6 +580,48 @@ private function add_user_action_notices( $notice = '' ) {
...
+				case 'order_restored' :
+					$this->add_notice( array(
+						'id'      => 'edd-order-restored',
+						'message' => __( 'The order has been restored.', 'easy-digital-downloads' )
+					) );
+					break;
+				case 'payment_deleted' :
+					$this->add_notice( array(
+						'id'      => 'edd-payment-deleted',
+						'message' => __( 'The payment has been deleted.', 'easy-digital-downloads' )
```
Comment (robincornett) [inline includes/admin/class-edd-notices.php:604]:
```suggestion
						'message' => __( 'The order has been deleted.', 'easy-digital-downloads' )
```
Just suggesting that we update this, and possibly the "payment note" message below, while these lines are being updated, so that the user facing language we are using is consistent.

File: includes/admin/class-edd-notices.php [hunk 2]
```diff
@@ -610,6 +580,48 @@ private function add_user_action_notices( $notice = '' ) {
...
+						'message' => __( 'The order has been deleted.', 'easy-digital-downloads' )
+					) );
+					break;
+				case 'email_sent' :
+					$this->add_notice( array(
+						'id'      => 'edd-payment-sent',
+						'message' => __( 'The purchase receipt has been resent.', 'easy-digital-downloads' )
+					) );
+					break;
+				case 'refreshed-reports' :
```
Comment (robincornett) [inline includes/admin/class-edd-notices.php:613]: This `refreshed-reports` wasn't removed from the `class-edd-notices` file; should it be removed from here (I think this is a duplicate)?

File: includes/admin/class-edd-notices.php [hunk 3]
```diff
@@ -610,6 +580,48 @@ private function add_user_action_notices( $notice = '' ) {
...
+					$this->add_notice( array(
+						'id'      => 'edd-refreshed-reports',
+						'message' => __( 'The reports have been refreshed.', 'easy-digital-downloads' )
+					) );
+					break;
+				case 'payment-note-deleted' :
+					$this->add_notice( array(
+						'id'      => 'edd-note-deleted',
+						'message' => __( 'The payment note has been deleted.', 'easy-digital-downloads' )
```
Comment (robincornett) [inline includes/admin/class-edd-notices.php:622]:
```suggestion
						'message' => __( 'The order note has been deleted.', 'easy-digital-downloads' )
```

File: includes/admin/class-edd-notices.php (hunk 2 above)
Comment (ashleyfae) [reply includes/admin/class-edd-notices.php]: Yes that was an oversight and should be removed here. Updated.

**Review by robincornett — APPROVED** [review]
