### PR TITLE
Remove currency formatting from File Downloads and New Customers graph

### LINKED ISSUE #9553: File Downloads report graph is formatting numbers as float and currency
### Expected behavior
When I view the file downloads report, I expect the graph to show integers (as you can't process a fractional download) and not be a currency.

### Actual behavior
The values put on the tooltips are formatted as currency and floats:
image

### Steps to reproduce the behavior
1) Have a site with file downloads
2) View Downloads > Reports > File Downloads

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 3.1

WordPress Version: All

### PR DESCRIPTION
**Pull request by zkawesome**
Fixes #9553 

Proposed Changes:
Removed the currency formatting from the File Downloads and New customers graph, so that it shows as an integer.
image

### CODE REVIEW

File: includes/admin/reporting/reports-callbacks.php [hunk 1]
```diff
@@ -118,7 +118,7 @@ function edd_overview_sales_earnings_chart() {
 
 		// Loop through each date there were sales/earnings, which we queried from the database.
 		foreach ( $earnings_results as $earnings_result ) {
-			$date_of_db_value = new DateTime( $earnings_result->date, $timezone );
+			$date_of_db_value = edd_get_edd_timezone_equivalent_date_from_utc( EDD()->utils->date( $earnings_result->date ) );
```
Comment (robincornett) [inline includes/admin/reporting/reports-callbacks.php:121]: I think this change and line 146 are really from a different issue/PR and should be removed from this? Otherwise the PR looks good.

Comment (cklosowski) [reply includes/admin/reporting/reports-callbacks.php:121]: @zkawesome I think robin is right here, looks like this is from the #9278 PR

**Review by robincornett — APPROVED** [review]
