### PR TITLE
Fix customer list table tab URLs

### LINKED ISSUE #7771: 3.0 - Customer List Tables Tabbed Navigation URLs Can Be Incorrect
### Expected behavior
The tab navigation links above the customers list tables should take me to a link showing all customers/emails/physical addresses.

### Actual behavior
Using the physical addresses table as an example, but the emails table is similarly affected: if I click the customer's name to view all addresses related to that customer, the tabbed navigation link for Physical Addresses is updated to this:

```
https://edd30.local/wp-admin/edit.php?post_type=download&page=edd-customers&page_type=physical&s=c%3A84
```
 So I am unable to return to an unfiltered/non-search view. All three tabs are affected, but I don't see a similar filter link in the main customer table rows.

### Steps to reproduce the behavior
1) in a 3.0 site, visit Downloads > Customers
2) then click on either the Email Addresses or Physical Addresses tab
3) click on a customer name to view all related addresses (filtered view)
4) try clicking on one of the tabs at the top of the page again

### Information (if a specific version is affected):
PHP Version: all
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
Related: #7762

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #7771

### CODE REVIEW

File: includes/admin/customers/customers.php [hunk 1]
```diff
@@ -36,10 +36,12 @@ function edd_customers_page_primary_nav( $active_tab = '' ) {
...
-			) );
+			$tab_url = edd_get_admin_url(
+				array(
+					'page'      => 'edd-customers',
+					'page_type' => esc_attr( $tab_id ),
+				)
+			);
 
 			// Remove the section from the tabs so we always end up at the main section
 			$tab_url = remove_query_arg( 'section', $tab_url );
```
Comment (robincornett) [inline includes/admin/customers/customers.php:47]: I am not sure that this use of `remove_query_arg` is necessary.

Comment (ashleyfae) [reply includes/admin/customers/customers.php:47]: To me that looks like left over copy paste from where `section` is used in the settings. I do not believe it's needed.

File: includes/admin/customers/customers.php [hunk 2]
```diff
@@ -36,10 +36,12 @@ function edd_customers_page_primary_nav( $active_tab = '' ) {
...
 
 			// Remove
-			$tab_url = add_query_arg( array(
-				'settings-updated' => false,
-				'page_type'        => $tab_id
-			) );
+			$tab_url = edd_get_admin_url(
+				array(
+					'page'      => 'edd-customers',
+					'page_type' => esc_attr( $tab_id ),
```
Comment (ashleyfae) [inline includes/admin/customers/customers.php:42]:
```suggestion
					'page_type' => urlencode( $tab_id ),
```

**Review by ashleyfae — CHANGES_REQUESTED** [review]

**Review by ashleyfae — APPROVED** [review]
