### PR TITLE
issue/7992 - 3.0 - Prevent Duplicate Tax Rate Additions/Activations

### LINKED ISSUE #7992: 3.0 - Taxes - Block Activating Multiple Country Wide Rates in UI
### Expected behavior

When an existing country-wide rate is activated any other rates that apply to the same full country should not be allowed to be activated.

### Actual behavior

Duplicate tax rates that get migrated can be activated after the fact.

### Steps to reproduce the behavior
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7602

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`/`issue/7602`

Any other relevant information:

Blocked from adding via UI in #6037 and deactivated during migration in #7602

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #7992

Proposed Changes:
1. Prevent duplicate tax rates from being added or activated in the Tax Rate UI.

### CODE REVIEW

File: assets/js/admin/settings/tax-rates/views/table-add.js [hunk 1]
```diff
@@ -154,26 +155,29 @@ const TableAdd = wp.Backbone.View.extend( {
...
+
 		if ( existingCountryWide.length > 0 ) {
-			alert( i18n.multipleCountryWide.replace( '%s', this.model.get( 'country' ) ) );
+			const regionString = '' === this.model.get( 'region' )
+				? ''
+				: ': ' + this.model.get( 'region' );
+
+			const taxRateString = this.model.get( 'country' ) + regionString;
+
+			alert( i18n.multipleCountryWide.replace( '%s', taxRateString ) );
```
Comment (robincornett) [inline assets/js/admin/settings/tax-rates/views/table-add.js:180]: On the alert, the text is displaying the escaped values for the quotes:

>Duplicate tax rates are not allowed. Please deactivate the existing &quot;US: TN&quot; tax rate before adding or activating another.

**Review by robincornett — APPROVED** [review]

**Review by LisaCee — APPROVED** [review]
- [x] Multiple country-wide tax rates
- [x] Duplicate-from-migration tax rates
- [x] Duplicate country/region tax rates

**Review by ashleyfae — APPROVED** [review]
