### PR TITLE
issue/7640 - Set Orders to "Partially Refunded" When Refunding an Order Item

### LINKED ISSUE #7640: 3.0 - Partial refunds not changing original order status to "partially_refunded"
### Expected behavior

When I refund part of an order, I expect the order's status to change to `partially_refunded` (both in the database and in the UI dropdown).

### Actual behavior

When I refund part of an order, the status in the database and UI remains `complete`. Also, there is no "Partially Refunded" dropdown option. I assume there is supposed to be one?

### Steps to reproduce the behavior
1) Have an order with at least two order items.
2) Refund just one of the order items.
3) The refund record will be created, but the original order status remains as "Completed".

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #7640 

Proposed Changes:
1. Set an Order status to "Partially Refunded" when one or more, but not all, Order Items are refunded.

### CODE REVIEW

File: includes/orders/functions/refunds.php [hunk 1]
```diff
@@ -36,7 +36,7 @@ function edd_is_order_refundable( $order_id = 0 ) {
 	}
 
 	// Only completed orders can be refunded.
-	if ( 'complete' !== $order->status ) {
+	if ( ! in_array( $order->status, array( 'complete', 'publish', 'partially_refunded', true ) ) ) {
```
Comment (ashleyfae) [inline includes/orders/functions/refunds.php]: What's the `true` for? Or was that meant to be outside the `array()` ?

Comment (spencerfinnell) [reply includes/orders/functions/refunds.php]: It tells `in_array()` to a strict type check recommended by WPCS: https://github.com/WordPress/WordPress-Coding-Standards/blob/d2ef2b5370dca0a11c7735bd9e14d711f8e18f32/WordPress/Sniffs/PHP/StrictInArraySniff.php

Comment (spencerfinnell) [reply includes/orders/functions/refunds.php]: Edit: Oh, yes. ☕️
