### PR TITLE
Issue/8764

### LINKED ISSUE #8764: 3.0 - Third parameter passed to `edd_log_file_download_download_files` filter is in different format than in pre-3.0 versions
Before EDD 3.0, third parameter passed to `edd_log_file_download_download_files` filter contained post meta values of `file_download` log post. Those meta values [were retrieved](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/5657a2b4355874b30a2a08d0b79162a739f609ef/includes/admin/reporting/class-file-downloads-logs-list-table.php#L359-L374) by using `get_post_custom()` function. That function returns all meta values of a post. Which means parameter was array in format `'meta_key' => array( 'meta_value_1', 'meta_value_2'...)`. In EDD 3.0, that array was [changed](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/8128b5383cd3610778da33e27b8aa35f8b797701/includes/admin/reporting/class-file-downloads-logs-list-table.php#L162-L169) to format `'meta_key' => 'meta_value'`. Code that referenced meta value in a format `$meta['meta_key'][0]` doesn't work anymore, and it can create a bug.

### PR DESCRIPTION
**Pull request by ashleyfae**
Fixes #8764

Proposed Changes:
1. Moves log file retrieval logic into a new method `get_log_files()` to clean things up a bit.
2. Retrieve all meta via `$meta = edd_get_file_download_log_meta( $log->id );` as a starting point.
3. When adding backwards compat meta, ensure values are an array.

### CODE REVIEW

File: includes/admin/reporting/class-file-downloads-logs-list-table.php [hunk 1]
```diff
@@ -210,6 +168,76 @@ function get_logs( $log_query = array() ) {
...
+			: array();
+
+		/*
+		 * Build up an array of meta.
+		 */
+		$meta = edd_get_file_download_log_meta( $log->id );
+
+		// These meta keys no longer exist, but we need to create them for use in the filter.
+		$backwards_compat_meta = array(
+			'_edd_log_user_info'  => $user_info,
```
Comment (robincornett) [inline includes/admin/reporting/class-file-downloads-logs-list-table.php:219]: Comparing a var_dump  from 2.11 with this PR, I think there also needs to be this line:

```php
'_edd_log_customer_id' => $customer->id,
```

Noting that my 2.11 log data does not include the `user_info` array:
```
array (size=6)
  '_edd_log_customer_id' => 
    array (size=1)
      0 => string '228' (length=3)
  '_edd_log_user_id' => 
    array (size=1)
      0 => string '1' (length=1)
  '_edd_log_file_id' => 
    array (size=1)
      0 => string '1' (length=1)
  '_edd_log_ip' => 
    array (size=1)
      0 => string '127.0.0.1' (length=9)
  '_edd_log_payment_id' => 
    array (size=1)
      0 => string '3463' (length=4)
  '_edd_log_price_id' => 
    array (size=1)
      0 => string '0' (length=1)
```

But if it's supposed to be there and I just don't happen to have it, that's fine, too. Other than the `customer_id`, this PR makes the `$meta` match the values in 2.x.

Comment (ashleyfae) [reply includes/admin/reporting/class-file-downloads-logs-list-table.php:219]: I'm inclined to say we keep it anyway because I don't know why it was there and it won't do any harm to keep it. :shrug:

**Review by robincornett — APPROVED** [review]
