### PR TITLE
#8452 Link to Usage Tracking Info

### LINKED ISSUE #8452: 3.0 - Correct link to usage tracking documentation
### Expected behavior
When I click on the link in our tracking subsection of the general settings, I expect it to go to a page about our usage tracking.

### Actual behavior
When I click on the link it goes to a 404 because the page is in draft and also unfinished.

### Steps to reproduce the behavior
Go to Settings - > General - > Tracking - > Usage tracking - > This is what we track
That goes to https://easydigitaldownloads.com/tracking/ but it should probably go to https://docs.easydigitaldownloads.com/article/1419-what-information-will-be-tracked-by-opting-into-usage-tracking

Any other relevant information:
To my knowledge, the /tracking/ page has never actually existed. @SDavisMedia appears to have encountered the link to nowhere when testing 3.0 and took it upon himself to draft the page. We could _redirect_ that page to our docs OR just change the link to go directly to the doc and toss /tracking/ in the trash.

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #8452 

Proposed Changes:
1. Correct link to tracking usage
2. Add numbered placeholders and information for translators

### CODE REVIEW

**Review by robincornett — APPROVED** [review]

File: includes/admin/settings/register-settings.php [hunk 1]
```diff
@@ -569,8 +569,9 @@ function edd_get_registered_settings() {
 						'name'  => __( 'Usage Tracking', 'easy-digital-downloads' ),
 						'check' => __( 'Allow',          'easy-digital-downloads' ),
 						'desc'  => sprintf(
-							__( 'Help us make Easy Digital Downloads better by opting into anonymous usage tracking. <a href="%s" target="_blank">Here is what we track</a>.<br>If you opt-in here and to <a href="%s">our newsletter</a>, we will email you a discount code for our <a href="%s" target="_blank">extension shop</a>.', 'easy-digital-downloads' ),
-							esc_url( 'https://easydigitaldownloads.com/tracking/' ),
+							/* translators: %1$s Link to tracking information, do not translate. %2$s Link to EDD newsleter, do not translate. %3$s Link to EDD extensions, do not translate */
+							__( 'Help us make Easy Digital Downloads better by opting into anonymous usage tracking. <a href="%1$s" target="_blank">Here is what we track</a>.<br>If you opt-in here and to <a href="%2$s">our newsletter</a>, we will email you a discount code for our <a href="%3$s" target="_blank">extension shop</a>.', 'easy-digital-downloads' ),
```
Comment (ashleyfae) [inline includes/admin/settings/register-settings.php:573]: While we're here, let's make the newsletter link open in a new tab like the others do.

**Review by ashleyfae — APPROVED** [review]
