### PR TITLE
issue/7667 - Use Advanced Filters in Logs

### LINKED ISSUE #7667: 3.0: Alignment and margins of filters in Tools > Logs > File Downloads messed up
## Bug Report
The alignment and margins of the filters in Tools > Logs is very messy:
image

WordPress latest and Chrome on Ubuntu.

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #7667

Proposed Changes:
1. Simplify alignments for filtering.
2. Ensure Advanced Filters can be used on all admin pages.
3. Add additional Log filters to Advanced Filters.

### CODE REVIEW

File: includes/admin/reporting/class-base-logs-list-table.php [hunk 1]
```diff
@@ -465,17 +465,29 @@ public function filter_bar_items() {
 
 		<?php endif; ?>
 
-		<span id="edd-after-core-filters">
-			<?php do_action( 'edd_payment_advanced_filters_after_fields' ); ?>
+		<?php if ( has_action( 'edd_payment_advanced_filters_after_fields' ) ) : ?>
+		<span id="edd-advanced-filters">
+			<input type="button" class="edd-advanced-filters-button button-secondary" value="<?php esc_html_e( 'More', 'easy-digital-downloads' ); ?>"/>
```
Comment (ashleyfae) [inline includes/admin/reporting/class-base-logs-list-table.php]:
```suggestion
			<input type="button" class="edd-advanced-filters-button button-secondary" value="<?php esc_attr_e( 'More', 'easy-digital-downloads' ); ?>"/>
```

File: includes/admin/reporting/class-base-logs-list-table.php [hunk 2]
```diff
@@ -465,17 +465,29 @@ public function filter_bar_items() {
...
+
+						<?php do_action( 'edd_payment_advanced_filters_after_fields' ); ?>
+					</fieldset>
+				</span>
+			</div>
+		</span>
+		<?php endif; ?>
 
-			<input type="submit" class="button-secondary" value="<?php _e( 'Filter', 'easy-digital-downloads' ); ?>"/>
+		<input type="submit" class="button-secondary" value="<?php _e( 'Filter', 'easy-digital-downloads' ); ?>"/>
```
Comment (ashleyfae) [inline includes/admin/reporting/class-base-logs-list-table.php]:
```suggestion
		<input type="submit" class="button-secondary" value="<?php esc_attr_e( 'Filter', 'easy-digital-downloads' ); ?>"/>
```
