### PR TITLE
issue/5684 - Discounts with multiple exclusions can be applied to excluded products

### LINKED ISSUE #5684: Discounts with multiple exclusions can be applied to excluded products
When a discount code has multiple downloads excluded, the code can be applied on the checkout when an excluded item is in the cart. The total amount isn't reduced, but the discount code is attached to the payment and counted as being used.

Steps to reproduce:
- Create new discount code, add multiple items to the Exclude Downloads list.
- Add one of the excluded items to the cart.
- Apply the discount code. Note that the code is applied.
- Complete purchase.

When viewing the payment details, you can see the code attached to the payment. The discount code's uses count is increased as well.

When a discount code has only one exclusion, it is properly blocked from being applied.

### PR DESCRIPTION
**Pull request by sunnyratilal**
Fixes #5684

### CODE REVIEW

File: includes/class-edd-discount.php [hunk 1]
```diff
@@ -1606,72 +1606,57 @@ public function is_product_requirements_met( $set_error = true ) {
...
-			switch( $this->product_condition ) {
-
+			switch ( $this->product_condition ) {
 				case 'all' :
-
 					// Default back to true
 					$return = true;
 
 					foreach ( $product_reqs as $download_id ) {
-
```
Comment (pippinsplugins) [inline includes/class-edd-discount.php]: Please don't remove this kind of whitespace. Let the code breath.

**Comment by sunnyratilal** [comment]
@pippinsplugins Whitespace re-added.

**Comment by pippinsplugins** [comment]
Thanks.

Let's hold off on merging this until tests are fixed. CC @cklosowski
