### PR TITLE
Fix division by zero error

### LINKED ISSUE #7613: Division by zero warnings in cart
## Bug Report
Got this error in my error log:

> Division by zero in /wp-content/plugins/easy-digital-downloads/includes/cart/class-edd-cart.php on line 689

I'm not sure what cart item (+discount?) exactly triggers this but it seems like an easy fix?

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.20

WordPress Version: 4.9

Any other relevant information:

### PR DESCRIPTION
**Pull request by robincornett**
Adds the additional suggested fix from #6901. In some cases, it was
still possible for the items subtotal to be 0, which caused a
mathematical error.

Fixes #7613

### CODE REVIEW

File: includes/cart/class-edd-cart.php [hunk 1]
```diff
@@ -686,7 +686,8 @@ public function get_item_discount_amount( $item = array(), $discount = false ) {
 								}
 							}
 
-							$subtotal_percent  = ( ( $price * $item['quantity'] ) / $items_subtotal );
+							$subtotal_quantity = ( $price * $item['quantity'] );
+							$subtotal_percent  = ! empty( $items_subtotal ) ? ( $subtotal_quantity / $items_subtotal ) : 0;
```
Comment (cklosowski) [inline includes/cart/class-edd-cart.php]:
```suggestion
							$item_subtotal       = ( $price * $item['quantity'] );
							$subtotal_percent  = ! empty( $items_subtotal ) ? ( $item_subtotal / $items_subtotal ) : 0;
```
