### PR TITLE
#8374 Redirect After Permanently Deleting

### LINKED ISSUE #8374: 3.0 - Permanently delete trashed order to return on the same page
### Expected behavior
When I click the Permanently Delete link next to an oder in the trash it should return me back to the Trash section.

### Actual behavior
Instead it redirects back to the ALL section which if not being careful and thinking you are back on the Trash section you could delete real orders

### Steps to reproduce the behavior
1) Trash an order
2) In the Orders filter section click on Trash then Delete permanently a trashed order

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): 3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #8374 

Proposed Changes:
1. Redirect to trashed orders after permanently deleting order
2. Escaping for function
3. Update doc block typo and param

I'm not quite sure the difference between this function and the one right above it, `edd_trigger_purchase_delete`.  I would love to clarify in the descriptions, once it is explained.

### CODE REVIEW

File: includes/admin/payments/actions.php [hunk 1]
```diff
@@ -262,24 +262,34 @@ function edd_trigger_purchase_delete( $data ) {
...
 
-		edd_redirect( admin_url( '/edit.php?post_type=download&page=edd-payment-history&edd-message=payment_deleted' ) );
+		$redirect_link = add_query_arg(
+			array(
+				'post_type'   => 'download',
+				'page'        => 'edd-payment-history',
+				'edd-message' => 'payment_deleted',
+				'status'      => 'trash',
+			),
+			admin_url( 'edit.php' ),
```
Comment (robincornett) [inline includes/admin/payments/actions.php:290]: Although this is totally working as it is, we could use `edd_get_admin_base_url` here instead of the `admin_url` function and remove the `post_type` parameter.

File: includes/admin/payments/actions.php [hunk 2]
```diff
@@ -262,24 +262,34 @@ function edd_trigger_purchase_delete( $data ) {
...
  */
 function edd_trigger_destroy_order( $data ) {
+
 	if ( wp_verify_nonce( $data['_wpnonce'], 'edd_payment_nonce' ) ) {
 
 		$payment_id = absint( $data['purchase_id'] );
 
 		if ( ! current_user_can( 'delete_shop_payments', $payment_id ) ) {
-			wp_die( __( 'You do not have permission to edit this payment record', 'easy-digital-downloads' ), __( 'Error', 'easy-digital-downloads' ), array( 'response' => 403 ) );
+			wp_die( esc_html_e( 'You do not have permission to edit this payment record', 'easy-digital-downloads' ), esc_html_e( 'Error', 'easy-digital-downloads' ), array( 'response' => 403 ) );
```
Comment (robincornett) [inline includes/admin/payments/actions.php:278]: Not sure, but would it make sense to go ahead and update the verbiage here to use "order" instead of "payment record"?

**Review by robincornett — COMMENTED** [review]
This totally works, and is a much better user experience--just a suggestion and a question.

File: includes/admin/payments/actions.php (hunk 1 above)
Comment (LisaCee) [reply includes/admin/payments/actions.php:290]: I thought about that, but isn't `edd_get_admin_base_url` a 3.0 function?  I wasn't sure about having to add an if/else here.

Comment (robincornett) [reply includes/admin/payments/actions.php:290]: Yes, but it's fine since this is going directly into 3.0 itself instead of an extension--it's the one time we can be sure the function will exist. No condition needed. :)

**Comment by ashleyfae** [comment]
> I'm not quite sure the difference between this function and the one right above it, `edd_trigger_purchase_delete`. I would love to clarify in the descriptions, once it is explained.

From what I can tell, `edd_trigger_purchase_delete()` is the 2.9 equivalent of `edd_trigger_destroy_order()`. In 2.9, `edd_trigger_purchase_delete()` was responsible for handling payment deletions. In 3.0 that's not used at all and `edd_trigger_destroy_order()` has replaced it.

With that in mind, @LisaCee you're welcome to move `edd_trigger_purchase_delete()` (and the `add_action()` hook below it) to `admin/admin-deprecated-functions.php`

File: includes/admin/payments/actions.php [hunk 3]
```diff
@@ -239,47 +239,33 @@ function edd_update_payment_details( $data = array() ) {
...
  */
 function edd_trigger_destroy_order( $data ) {
+
 	if ( wp_verify_nonce( $data['_wpnonce'], 'edd_payment_nonce' ) ) {
 
 		$payment_id = absint( $data['purchase_id'] );
 
 		if ( ! current_user_can( 'delete_shop_payments', $payment_id ) ) {
-			wp_die( __( 'You do not have permission to edit this payment record', 'easy-digital-downloads' ), __( 'Error', 'easy-digital-downloads' ), array( 'response' => 403 ) );
+			wp_die( esc_html_e( 'You do not have permission to edit this order', 'easy-digital-downloads' ), esc_html_e( 'Error', 'easy-digital-downloads' ), array( 'response' => 403 ) );
```
Comment (robincornett) [inline includes/admin/payments/actions.php:255]: These should both be just `esc_html__`, rather than echoing. I would also maybe go ahead and add a period to the end of the sentence--feel like it looks a little bit funny on the die screen without it, but I know it wasn't there before, so I am fine without it.

Comment (LisaCee) [reply includes/admin/payments/actions.php]: The missing period was bugging me, too.  :joy:

**Review by robincornett — APPROVED** [review]

**Review by ashleyfae — APPROVED** [review]
