### PR TITLE
issue/8619 - Manual Orders - Support Inclusive Taxes

### LINKED ISSUE #8619: 3.0 - Manual Orders - Support Inclusive Taxes
### Expected behavior

When manually creating an order on a site that uses inclusive tax rates the calculations should be correct.

### Actual behavior

Taxes are still being added and displayed to amounts that do not need them.

### Steps to reproduce the behavior
1) Set "Prices Include Tax" to "Yes, I will enter prices inclusive of tax"
2) Create a manual order that has a tax rate applied.

### Information (if a specific version is affected):
PHP Version:
EDD Version (or branch): `release/3.0`
WordPress Version:

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #8619

Proposed Changes:
1. Support inclusive tax calculations when manually creating an order.

### CODE REVIEW

**Review by LisaCee — APPROVED** [review]
- [x] Taxes enabled, exclusive of tax
- [ ] Taxes enabled, inclusive of tax
- [ ] Taxes enabled, inclusive of tax with discount
_Percentage discount taken from inclusive price_
- [ ] Taxes enabled, inclusive of tax with taxed fee and discount
_It took me a while to figure out the math here. Amount (unit price - tax) - Discount + Fee__
- [ ] Taxes enabled, inclusive of tax with untaxed fee and discount
- [ ] Taxes enabled, inclusive of tax with credit and discount
- [ ] Taxes disabled but inclusive prices
_The total is right here, but it seems odd that the tax rate is listed, but had no dollar value. Probably unrelated to this PR, but I just wanted to note it._

File: assets/js/admin/orders/order-overview/models/state.js [hunk 1]
```diff
@@ -161,9 +187,16 @@ export const State = Backbone.Model.extend(
 						return amount += +adjustment.get( 'subtotal' );
 					}
 				},
-				this.getSubtotal()
+				this.getSubtotal( includeTaxInSubtotal )
 			);
 
+			if ( true === this.hasInclusiveTax() ) {
+				// Fees always have tax added.
```
Comment (LisaCee) [inline assets/js/admin/orders/order-overview/models/state.js:194]: I'm not sure if this is true anymore, since it was changed to a toggle as described in this [comment](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8581#issuecomment-827792453). Same for the comment in order-adjustment.js.

Comment (spencerfinnell) [reply assets/js/admin/orders/order-overview/models/state.js:194]: @LisaCee I think the comment should really be:

```
// Fees always have tax added exclusively
```

You can choose to add tax or not, but if you do add tax, it will be added to the entered value (exclusive tax).

**Review by ashleyfae — APPROVED** [review]

**Review by robincornett — APPROVED** [review]
