### PR TITLE
#8068 "Download Requirements" Toggle

### LINKED ISSUE #8068: 3.0 - Discount "Download Requirements" conditions toggle with each product added
### Expected behavior
Once a download/product has been added to the "Download Requirements" on the Discounts screens, I expect the product conditions field to show, and to persist.

### Actual behavior
When I add one product to the "Download Requirements", the product conditions select input shows. When I add a second one, the input is toggled to hide. With each new product added, the conditions toggle between show/hide.

### Steps to reproduce the behavior
1) Create a new discount.
2) Add a product to the "Download Requirements" field. The product conditions will show.
3) Add another product; the conditions input will disappear.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0 (this does not toggle in 2.9.x)
WordPress Version: 5.4.2

Any other relevant information:
It looks like [the script is toggling the conditions input every time the download requirements input changes](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/discounts/index.js#L19), not just when the first/only item is added/removed.

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #8068 

Proposed Changes:
1.  Changed event to `show` rather than `toggle` when items are added to list

I would have liked to have these fields revert back to `hidden` when all items are removed from the list, but I haven't been able to figure that out with jQuery yet.

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
Is there a way to set it up to show once the value is not empty, but then hide again if I remove all of the products? The original issue is fixed--the input is no long disappearing on me, but if it could hide if there are no products, I think that would be nice.

File: assets/js/admin/discounts/index.js [hunk 1]
```diff
@@ -17,6 +16,6 @@ jQueryReady( () => {
 	 * Show/hide conditions based on input value.
 	 */
 	products.change( function() {
-		$( '#edd-discount-product-conditions' ).toggle( products.val() );
+		$( '#edd-discount-product-conditions' ).show( products.val() );
```
Comment (spencerfinnell) [inline assets/js/admin/discounts/index.js:19]: @LisaCee I believe the original implementation meant to use `.toggle()` via the `display` argument: https://api.jquery.com/toggle/#toggle-display

However `products.val()` is returning `null` or an array here and jQuery seems to consider both truthy in this case. Instead the value should be checked to not be null and that be used to determine the `display` boolean.

**Review by spencerfinnell — CHANGES_REQUESTED** [review]

File: assets/js/admin/discounts/index.js [hunk 2]
```diff
@@ -16,6 +16,10 @@ jQueryReady( () => {
 	 * Show/hide conditions based on input value.
 	 */
 	products.change( function() {
-		$( '#edd-discount-product-conditions' ).show( products.val() );
+		if (products.val() !== null) {
+			$( '#edd-discount-product-conditions' ).show( products.val() );
+		} else if (products.val() === null ) {
```
Comment (ashleyfae) [inline assets/js/admin/discounts/index.js:21]: Could this just be `else` ?

Comment (spencerfinnell) [reply assets/js/admin/discounts/index.js:21]: @LisaCee The check for null can be done inside of `.toggle()`, like:

```js
$( '#edd-discount-product-conditions' ).toggle( null !== products.val() );
```

If condition side of `.toggle()` is `true` then the selector will to show, if it is false it will hide.

**Review by spencerfinnell — CHANGES_REQUESTED** [review]

File: assets/js/admin/discounts/index.js (hunk 2 above)
Comment (LisaCee) [reply assets/js/admin/discounts/index.js]: Much more elegant.  Thanks

**Review by spencerfinnell — APPROVED** [review]

**Review by robincornett — APPROVED** [review]
Working nicely for me!

**Review by ashleyfae — APPROVED** [review]
