### PR TITLE
Remap missing EDD_Payments_Query arguments #7845

### LINKED ISSUE #7845: 3.0 - EDD_Payments_Query missing some backwards compatibility in arg mapping
### Expected behavior

When I use `EDD_Payments_Query` I expect all parameters that worked in 2.9 to still work in 3.0 and get remapped accordingly.

### Actual behavior

Not all arguments get remapped.

#### `meta_key`

Previously you could pass in `meta_key` without a value. But now, `meta_key` only gets included if `meta_value` was also provided: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-payments-query.php#L571 This should not be necessary.

#### "Individual" date arguments

None of the "individual" date arguments get mapped. Such as: `year`, `month`, `day`. Also `hour` used to work, though it's not documented in the defaults.

#### `number` including support for `-1`

`number` used to be accepted. But the remapping is only looking for `posts_per_page`. Also we need to consider support for `-1` to fetch all (related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7748)

There might be other issues as well. These are just the ones that were found in Software Licensing: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1644

### Steps to reproduce the behavior
1) Have Software Licensing installed.
2) Visit the SL Upgrades Report.
3) The results on the graph will be inaccurate. This is due to the query not working as expected.

Alternatively:

1) Have Software Licensing installed.
2) Manually run this: `$renewals = edd_sl_get_renewals_by_date( 8, 5, 2020, 12 );`
3) Note how results are inaccurate.

The arguments being passed in to `EDD_Payments_Query` to run that are:

```
array (
  'number' => -1,
  'status' => 
  array (
    0 => 'revoked',
    1 => 'publish',
    2 => 'complete',
  ),
  'meta_key' => '_edd_sl_is_renewal',
  'year' => 2020,
  'month' => 5,
  'fields' => 'ids',
  'day' => 8,
  'hour' => 12,
)
```

(this is before merging with defaults)

But after the remapping, we only come out with these:

```
array (
  'orderby' => 'id',
  'type' => 'sale',
  'order' => 'DESC',
  'status__in' => 
  array (
    0 => 'revoked',
    2 => 'complete',
    3 => 'complete',
  ),
)
```

Most notably missing to actually make this query work are: meta_key and all the date parameters.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by ashleyfae**
Fixes #7845

Proposed Changes:
1.`meta_key` can now be included without a corresponding `meta_value`.
2. Add support for "individual" date intervals: `array( 'year', 'month', 'week', 'day', 'hour', 'minute', 'second' ) `
3. Add support for `number`.
4. If `-1` is passed as `number` then `nopaging` is set to `true`.
5. If `nopaging` is set to `true` then this is meant to show all results. This was doing `unset( $arguments['number'] )` but the default in `edd_get_orders()` was then just being used instead, which was effectively setting the number to 30. So this has been adjusted to set the number to a really large integer instead.

### CODE REVIEW

File: includes/payments/class-payments-query.php [hunk 1]
```diff
@@ -609,12 +618,22 @@ private function remap_args() {
 			$arguments['date_created_query']['inclusive'] = true;
 		}
 
+		if ( isset( $this->initial_args['number'] ) ) {
+			if ( -1 == $this->initial_args['number'] ) {
```
Comment (spencerfinnell) [inline includes/payments/class-payments-query.php:622]: Is it safe to do a strict check here?

Comment (ashleyfae) [reply includes/payments/class-payments-query.php:622]: You could technically pass in the number as a string and if we do a strict check here then it wouldn't work the way we want (to fetch all results).

Both of these should work the same:

```php
$query = new EDD_Payments_Query( array(
	'number' => -1
) );
$query->get_payments();
```

```php
$query = new EDD_Payments_Query( array(
	'number' => '-1'
) );
$query->get_payments();
```

Comment (spencerfinnell) [reply includes/payments/class-payments-query.php:622]: What about forcing `$this->initial_args['number']` to a string -- that seems to be the most common?

Comment (ashleyfae) [reply includes/payments/class-payments-query.php:622]: If we're going to force it to something I think I'd rather do an integer. That's what all our default number values are already.

Is there something in particular you're concerned about here with not using a strict check though?

Comment (spencerfinnell) [reply includes/payments/class-payments-query.php:622]: No big deal since we don't technically enforce it, but ideally it will eventually become a rule: https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/PHP/StrictComparisonsSniff.php

**Comment by ashleyfae** [comment]
Updated to remap `post__not_in` as well. Found that issue while testing and fixing #7910
