### PR TITLE
Remove edd-admin-orders script from orders

### LINKED ISSUE #7882: 3.0 - JavaScript error while viewing admin Orders table
### Expected behavior

I expect to not get any JavaScript errors.

### Actual behavior

When I visit the admin Orders table I get the following JavaScript error:

Screenshot from 2020-05-13 13-26-20

Coming from `assets/js/admin/orders/order-details/address.js` line `21`

### Steps to reproduce the behavior
1) Go to Downloads > Orders.
2) Check your browser console to see the error.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #7882 

Proposed Changes:
1. Remove `edd-admin-orders` script from orders

I don't quite understand the technicalities of what this is doing, but I can confirm that the JavaScript error has gone away in the console.

### CODE REVIEW

File: includes/admin/payments/view-order-details.php [hunk 1]
```diff
@@ -18,6 +18,11 @@
  * @since 1.6
  * @since 3.0 Updated to use the new EDD\Orders\Order object.
  */
+
+wp_enqueue_script( 'edd-admin-orders' );
+// Enqueued for backwards compatibility. Empty file.
+wp_enqueue_script( 'edd-admin-payments' );
+
```
Comment (spencerfinnell) [inline includes/admin/payments/view-order-details.php:25]: This can be moved under the potential `wp_die()` calls so they don't get enqueued until we know we have something to display.

File: includes/admin/payments/view-refund.php [hunk 2]
```diff
@@ -18,6 +18,11 @@
  * @since 3.0
  */
 function edd_view_refund_page_content() {
+
+	wp_enqueue_script( 'edd-admin-orders' );
+	// Enqueued for backwards compatibility. Empty file.
+	wp_enqueue_script( 'edd-admin-payments' );
+
```
Comment (spencerfinnell) [inline includes/admin/payments/view-refund.php:25]: This can be moved under the potential `wp_die()` calls so they don't get enqueued until we know we have something to display.
