### PR TITLE
Fixing reporting warnings of undefined variables #7673

### LINKED ISSUE #7673: 3.0 - Download related reports throw warnings due to missing filters variable.
### Expected behavior
When viewing the Downloads report, no errors should be present.

### Actual behavior
the downloads report throws warnings due to the fact that the `$filter` variable is never defined.\

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #7673 

Proposed Changes:
1. Correct references to the wrong `$filter` variable when getting the `$dates` ranges.

### CODE REVIEW

File: includes/admin/reporting/reports.php [hunk 1]
```diff
@@ -486,6 +486,7 @@ function edd_register_downloads_report( $reports ) {
 		$dates         = Reports\get_filter_value( 'dates' );
 		$exclude_taxes = Reports\get_taxes_excluded_filter();
 		$label         = $options[ $dates['range'] ];
+		$filter        = Reports\get_filters();
```
Comment (spencerfinnell) [inline includes/admin/reporting/reports.php]: We should remove `$filter` from the `use()` statements instead since it's not being used inside of the callbacks.

Comment (cklosowski) [reply includes/admin/reporting/reports.php]: I'll go ahead and verify that in all the registered ones. Will update this shortly.

Comment (cklosowski) [reply includes/admin/reporting/reports.php]: All set @spencerfinnell, let me know if this is better.
