### PR TITLE
Fix orders import tool

### LINKED ISSUE #8137: 3.0 - Errors when importing orders
### Expected behavior
When I import a CSV of orders, I expect it to run without errors.

### Actual behavior
I get errors:

```
[30-Sep-2020 13:56:30 UTC] PHP Notice:  Undefined property: wpdb::$customermeta in \wp-includes\wp-db.php on line 648
[30-Sep-2020 13:56:30 UTC] PHP Stack trace:
[30-Sep-2020 13:56:30 UTC] PHP   1. {main}() \wp-admin\admin-ajax.php:0
[30-Sep-2020 13:56:30 UTC] PHP   2. do_action() \wp-admin\admin-ajax.php:176
[30-Sep-2020 13:56:30 UTC] PHP   3. WP_Hook->do_action() \wp-includes\plugin.php:478
[30-Sep-2020 13:56:30 UTC] PHP   4. WP_Hook->apply_filters() \wp-includes\class-wp-hook.php:311
[30-Sep-2020 13:56:30 UTC] PHP   5. edd_do_ajax_import() \wp-includes\class-wp-hook.php:287
[30-Sep-2020 13:56:30 UTC] PHP   6. EDD_Batch_Payments_Import->process_step() \wp-content\plugins\easy-digital-downloads.30\includes\admin\import\import-functions.php:140
[30-Sep-2020 13:56:30 UTC] PHP   7. EDD_Batch_Payments_Import->create_payment() \wp-content\plugins\easy-digital-downloads.30\includes\admin\import\class-batch-import-payments.php:112
[30-Sep-2020 13:56:30 UTC] PHP   8. EDD_Batch_Payments_Import->set_customer() \wp-content\plugins\easy-digital-downloads.30\includes\admin\import\class-batch-import-payments.php:169
[30-Sep-2020 13:56:30 UTC] PHP   9. wpdb->__get() \wp-content\plugins\easy-digital-downloads.30\includes\admin\import\class-batch-import-payments.php:403
[30-Sep-2020 13:56:30 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE meta_key = '_canonical_import_id' AND meta_value = 1 LIMIT 1' at line 1 for query SELECT customer_id FROM  WHERE meta_key = '_canonical_import_id' AND meta_value = 1 LIMIT 1 made by do_action('wp_ajax_edd_do_ajax_import'), WP_Hook->do_action, WP_Hook->apply_filters, edd_do_ajax_import, EDD_Batch_Payments_Import->process_step, EDD_Batch_Payments_Import->create_payment, EDD_Batch_Payments_Import->set_customer
```

This is a 3.0 > 3.0 export/import; the behavior may be different exporting from 2.9 and importing to 3.0.

### Steps to reproduce the behavior
1) In 3.0, visit Downloads > Reports > Export.
2) Use "Export Orders" to export all store orders as a CSV.
3) Visit Downloads > Tools.
4) Reset the store (optional).
5) Visit Downloads > Tools > Import/Export.
6) Import the CSV using "Import Payment History" _(question: should this be "Import Orders" instead?)_

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.5.1

Any other relevant information:
The orders are importing, but the customer information is wonky--names are missing, and the "customer since" date is the date of the import, not the date of the first order. So all orders are showing "No Name" for the customer in the orders table, although the customer is selected in the order edit screen. This should also be done with full order information (my store is orders generated via CLI, so there is no address information).

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #8137

Proposed Changes:
1. Update `customer_id` database column usage to `edd_customer_id`.
2. Update tool title to Import Orders instead of Payment History.
3. Use `name` column from CSV when present (#8143).

### CODE REVIEW

File: includes/admin/import/class-batch-import-payments.php [hunk 1]
```diff
@@ -447,39 +454,46 @@ private function set_customer( $row ) {
...
-			if( empty( $customer->id ) ) {
+			if ( empty( $customer->id ) ) {
 
 				if ( ! $customer instanceof EDD_Customer ) {
-					$customer = new EDD_Customer;
+					$customer = new EDD_Customer();
 				}
+			}
+
+			$name = '';
```
Comment (ashleyfae) [inline includes/admin/import/class-batch-import-payments.php:464]: This isn't needed because it's always set no matter what in the following if/else statement.

File: includes/admin/import/class-batch-import-payments.php [hunk 2]
```diff
@@ -447,39 +454,46 @@ private function set_customer( $row ) {
...
-				if( ! empty( $canonical_id ) && (int) $canonical_id !== (int) $customer->id ) {
-					$customer->update_meta( '_canonical_import_id', $canonical_id );
-				}
-
+				$name = $first_name . ' ' . $last_name;
 			}
 
+			$customer->create(
+				array(
+					'name'  => $name,
```
Comment (ashleyfae) [inline includes/admin/import/class-batch-import-payments.php:489]: For improved clarity and less duplication, can you remove all the `sanitize_text_field()` calls on the `$name`, `$first_name`, and `$last_name` variables further up, then just do it _once_ right here? That will reduce it from 3 calls to just 1, and also make it easier to see that we're sanitizing at the end.

File: includes/admin/import/class-batch-import-payments.php [hunk 3]
```diff
@@ -447,39 +454,46 @@ private function set_customer( $row ) {
...
+					'email' => $email,
```
Comment (ashleyfae) [inline includes/admin/import/class-batch-import-payments.php:490]: It looks like `$email` could be not set. (This may have already been the case before your changes, but let's fix it anyway.)

**Review by ashleyfae — CHANGES_REQUESTED** [review]

**Comment by ashleyfae** [comment]
This is working well now. Just requesting one additional fix as noted here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8137#issuecomment-709302043

**Review by ashleyfae — APPROVED** [review]
