### PR TITLE
Keep extra user_info during order migration

### LINKED ISSUE #8350: 3.0 - Order migration should only remove core payment metadata
### Expected behavior
When I migrate orders from posts to the new orders table in 3.0, I expect my data to all be there.

### Actual behavior
If an extension stores any data inside of the `_edd_payment_meta`, specifically adding data to the `user_info`, it will be lost during migration.

### Steps to reproduce the behavior
1. Set up a 2.9 storefront with Simple Shipping and make some orders with shipping addresses.
2. Update to 3.0 and migrate the orders.
3. The shipping addresses are gone.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6

Any other relevant information:
Per @ashleyfae in Slack:
>In the migrator, we could match $user_info against a list of keys that we put there in EDD core. So that's:
id
email
first_name
last_name
discount
address

>I think that's it. If the `$user_info` array has more keys than that, then we save the extra data into meta to preserve it. That way the shipping info (and anything else people have thrown in) is never lost. So that's an EDD core change.

>So if $user_info contains id, email, first_name, and everything else I mentioned.. and also has shipping_address or whatever Simple Shipping names it, then we'd only store shipping_address in order meta (using the key user_info and the value is a serialized array with just array( 'shipping_address' => array() )
Then, we'd need a change at the end of this method: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L3089 to fetch user_info meta. If anything is in there, we have to merge the contents of that with $user_info here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L3163

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #8350

Proposed Changes:
1. During order migration, only removes core `user_info` from the payment meta--if anything is left, it's saved.
2. Adds a backwards compatibility check to the `setup_user_info` method in `EDD_Payment` to get the extra `user_info`.

### CODE REVIEW

File: includes/payments/class-edd-payment.php [hunk 1]
```diff
@@ -3160,6 +3160,12 @@ private function setup_user_info() {
 			);
 		}
 
+		// Check for old `user_info` meta which may still exist.
+		$old_meta = $this->get_meta( 'payment_meta' );
```
Comment (ashleyfae) [inline includes/payments/class-edd-payment.php:3164]: I think we should be able to just use `edd_get_order_meta()` here. That's preferable because it will bypass some of the old filters and backwards compat stuff that's in `$this->get_meta()`. I don't think we need all that here.

**Review by ashleyfae — COMMENTED** [review]
Ran a migration and this is working very well.

However, one thing I noticed is a ton of user info meta with `user_id` (note `user_id` instead of `id`).

How about we add that to our `$core_user_info` list, if it's not empty and is the same value as the normal `id`.

**Comment by robincornett** [comment]
Updated, but I was thinking about this with Simple Shipping yesterday and left a comment there...is it worth adding a filter to the list of core `user_info` keys so that an extension could add its key(s) to the array and then not create the order meta? So Simple Shipping could add its filter with its migration process and the shipping info would not be passed on to the payment meta, since the extension is taking care of it.

I was just thinking that with this as it stands, any orders with shipping will always have the `payment_meta` created and added, even if it's not necessary. Alternatively, the extension could remove the meta when it hooks into the migration. Just thinking out loud.

**Comment by ashleyfae** [comment]
> Updated, but I was thinking about this with Simple Shipping yesterday and left a comment there...is it worth adding a filter to the list of core `user_info` keys so that an extension could add its key(s) to the array and then not create the order meta? So Simple Shipping could add its filter with its migration process and the shipping info would not be passed on to the payment meta, since the extension is taking care of it.
> 
> I was just thinking that with this as it stands, any orders with shipping will always have the `payment_meta` created and added, even if it's not necessary. Alternatively, the extension could remove the meta when it hooks into the migration. Just thinking out loud.

Let's add a filter. :+1:

File: includes/admin/upgrades/v3/class-data-migrator.php [hunk 2]
```diff
@@ -735,6 +734,20 @@ public static function orders( $data = null ) {
 			'tax',
 		);
 
+		// Remove core keys from `user_info`.
+		$remaining_user_info = false;
+		if ( ! empty( $user_info ) ) {
+			$core_user_info      = apply_filters( 'edd_30_core_user_info', array( 'id', 'email', 'first_name', 'last_name', 'discount', 'address', 'user_id' ) );
```
Comment (ashleyfae) [inline includes/admin/upgrades/v3/class-data-migrator.php:740]: Let's also add some docs to explain why you might use this filter.

**Review by ashleyfae — APPROVED** [review]
