### PR TITLE
issue/6605 - Add sleep() if PayPal PDT is used.

### LINKED ISSUE #6605: Double PayPal payment processing
### Expected behavior
When a PayPal payment is submitted, I expect the user value to go up by the value of the transaction. I also expect the transaction to only send one notification email, and create only one license. That payment should also only have one set of log messages on the payment i.e. 'Status changed from Pending to Complete'.

### Actual behavior
At least half of the PayPal payments are being marked as complete twice. I have to watch for duplicate payment notification emails so I can delete the extra licenses generated ad recount the user totals. This may also affect report accuracy, but I haven't looked into that.
screen shot 2018-05-28 at 9 25 15 am

### Steps to reproduce the behavior
1. Submit a payment with the PayPal Standard gateway
2. After the IPN notification is received, the payment is processed twice.

### Possible fix
I've made this change on my site, but haven't yet verified if it solves the problem. This fix does not change the payment status unless it is different from the previous status.
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/functions.php#L292

if( $payment && $payment->ID > 0 && $payment->status !== $new_status ) {

### PR DESCRIPTION
**Pull request by sunnyratilal**
Fixes #6605

Proposed Changes:
1. Call `sleep()` on IPN actions if PDT is enabled too. PayPal PDT and IPN both sending data back to the site can cause a race condition to develop whereby the status of a payment is changed to `complete` twice triggering all the completed purchase actions to be triggered twice: double the license keys, double referrals in AffiliateWP etc.

### CODE REVIEW

File: includes/gateways/paypal-standard.php [hunk 1]
```diff
@@ -339,6 +339,18 @@ function edd_listen_for_paypal_ipn() {
 		edd_debug_log( 'PayPal IPN endpoint loaded' );
 
 		do_action( 'edd_verify_paypal_ipn' );
+
+		/**
+		 * This is necessary to delay execution of PayPal PDT and to avoid a race condition causing the order status
+		 * updates to be triggered twice.
+         *
+         * @since 2.9.4
```
Comment (pippinsplugins) [inline includes/gateways/paypal-standard.php]: Indention needs fixed here.

File: includes/gateways/paypal-standard.php [hunk 2]
```diff
@@ -334,11 +334,23 @@ function edd_process_paypal_purchase( $purchase_data ) {
  */
 function edd_listen_for_paypal_ipn() {
 	// Regular PayPal IPN
-	if ( isset( $_GET['edd-listener'] ) && $_GET['edd-listener'] == 'IPN' ) {
+	if ( isset( $_GET['edd-listener'] ) && 'IPN' === $_GET['edd-listener'] ) {
```
Comment (pippinsplugins) [inline includes/gateways/paypal-standard.php]: This should be run through `strtolower` if running a strict comparison.

File: includes/gateways/paypal-standard.php [hunk 3]
```diff
@@ -334,11 +334,23 @@ function edd_process_paypal_purchase( $purchase_data ) {
...
+		/**
+		 * This is necessary to delay execution of PayPal PDT and to avoid a race condition causing the order status
+		 * updates to be triggered twice.
+		 *
+		 * @since 2.9.4
+		 * @see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6605
+		 */
+		$token = edd_get_option( 'paypal_identity_token' );
+		if ( $token ) {
+			sleep( 5 );
```
Comment (pippinsplugins) [inline includes/gateways/paypal-standard.php]: This needs to come before `do_action( 'edd_verify_paypal_ipn' );`

Comment (sunnyratilal) [reply includes/gateways/paypal-standard.php]: Whoops, fixed. :)
