### PR TITLE
issue/7669 - Hide Irrelevant Report Endpoints Based on Filters

### LINKED ISSUE #7669: 3.0 - Reports - Hide Irrelevant Endpoints
### Explain your enhancement (please be detailed)

When a Report has filtering options for things like a specific Download report endpoints that aren't relevant to the specific Download should not be shown.

### Justification or use case

It is confusing to view File Downloads in the last 30 days for "Download B" but still see information about "Top 5 Downloads", "Average Per Customer", etc.

### LINKED ISSUE #7674: 3.0 - Reports - Download report for specific variation still shows pie charts for variations.
### Expected behavior
When viewing the reports of a variable priced product, but just a single variation, not all variations, the pie chart showing the variation purchase distribution should be hidden.

### Actual behavior
The pie chart for variation purchase distribution is still shown when a single price ID is selected.

### Steps to reproduce the behavior
1) Create and buy different variations of a downlaod
2) Visit the Downloads > Reports > Downloads and filter by a single variation of a product.
3) See that the pie charts sill show

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by spencerfinnell**
Closes #7669 
Closes #7674 

Proposed Changes:
1. Removes sortable metabox implementation of Report Tiles. Reimplements as standard output.
2. Adjusts Report Tile CSS for smaller devices.
3. Filters endpoints that get attached to report based on active filters.

### CODE REVIEW

**Comment by ashleyfae** [comment]
@spencerfinnell Was just reviewing this again and I'm hoping you can confirm something in the `Gateways` reports tab.

In this branch, when I'm on `All` gateways, I see a `Sales and Earnings` graph at the bottom. In `release/3.0` I do not see this graph. And for the life of me I can't make it appear. I'm inclined to think that was a bug. However, looking at the raw query, I think it was _intended_ to only display when filtering a specific gateway:

```mysql
SELECT COUNT(subtotal)     AS sales,
       SUM(subtotal)       AS earnings,
       YEAR(date_created)  AS year,
       MONTH(date_created) AS month,
       DAY(date_created)   AS day
FROM wp_edd_orders o
WHERE gateway = 'all'
  AND status IN ('complete', 'revoked')
  AND date_created >= '2020-03-01 08:00:00'
  AND date_created <= '2020-04-01 06:59:59'
GROUP BY YEAR(date_created), MONTH(date_created), DAY(date_created)
ORDER BY YEAR(date_created), MONTH(date_created), DAY(date_created) ASC
```

Notice `WHERE gateway = 'all'`

That leads me to think the current display in `issue/7669` should be reversed. The graph should NOT appear while on `All` gateways and it SHOULD appear when you've filtered down to a specific one.

Do you agree?

File: includes/admin/reporting/reports.php [hunk 1]
```diff
@@ -2028,25 +2060,6 @@ function edd_register_discounts_report( $reports ) {
...
 					},
 					'display_args'  => array(
-						'context'          => 'primary',
-						'comparison_label' => $label,
-					),
-				),
-			),
-		) );
-
-		$reports->register_endpoint( 'ratio_of_discounted_orders', array(
```
Comment (ashleyfae) [inline includes/admin/reporting/reports.php:2038]: This endpoint appears to have gone missing completely.

**Comment by spencerfinnell** [comment]
@ashleyfae Correct, showing "Earnings and Sales" for "All" gateways is just what is shown on the Overview. Updated to only show when viewing a specific gateway.
