### PR TITLE
Display excluded_products in Discount REST

### LINKED ISSUE #7418: excluded_products doesn't display in Discount REST API
### Expected behavior
When I visit listed REST URLs, I am not able to see exluded_products.

http://localhost/edd/edd-api/discounts/?key=c48a9e9f3a9b5c6f4f35b5bbee0d9699&token=e9660c28b6ce17e7c45de87f74638e33

http://localhost/edd/edd-api/discounts/?discount=694&key=c48a9e9f3a9b5c6f4f35b5bbee0d9699&token=e9660c28b6ce17e7c45de87f74638e33

### Actual behavior
When I visit the REST URLs, I should see the excluded_products.

### Steps to reproduce the behavior
1) Visit the http://localhost/edd/edd-api/discounts/?key=c48a9e9f3a9b5c6f4f35b5bbee0d9699&token=e9660c28b6ce17e7c45de87f74638e33

2) Visit the http://localhost/edd/edd-api/discounts/?discount=694&key=c48a9e9f3a9b5c6f4f35b5bbee0d9699&token=e9660c28b6ce17e7c45de87f74638e33

### PR DESCRIPTION
**Pull request by pmbaldha**
Fixes https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7418

Proposed Changes:
1. excluded_products added in the Discount REST

_Please do not submit PRs with minified CSS or JS files. This is managed at the time of release by the Core Team_

### CODE REVIEW

File: includes/api/class-edd-api.php [hunk 1]
```diff
@@ -1581,6 +1581,7 @@ public function get_discounts( $discount = null ) {
 				$discount_list['discounts'][$count]['product_requirements']  = edd_get_discount_product_reqs( $discount->ID );
 				$discount_list['discounts'][$count]['requirement_condition'] = edd_get_discount_product_condition( $discount->ID );
 				$discount_list['discounts'][$count]['global_discount']       = edd_is_discount_not_global( $discount->ID );
+				$discount_list['discounts'][$count]['excluded_products']  	= edd_get_discount_excluded_products( $discount->ID );
```
Comment (robincornett) [inline includes/api/class-edd-api.php:1584]:
```suggestion
				$discount_list['discounts'][$count]['excluded_products']     = edd_get_discount_excluded_products( $discount->ID );
```
(Just adjusting mid-line alignment to use spaces.)

File: includes/api/class-edd-api.php [hunk 2]
```diff
@@ -1604,6 +1605,7 @@ public function get_discounts( $discount = null ) {
 				$discount_list['discounts'][0]['product_requirements']       = edd_get_discount_product_reqs( $discount );
 				$discount_list['discounts'][0]['requirement_condition']      = edd_get_discount_product_condition( $discount );
 				$discount_list['discounts'][0]['global_discount']            = edd_is_discount_not_global( $discount );
+				$discount_list['discounts'][0]['excluded_products'] 	     = edd_get_discount_excluded_products( $discount->ID );
```
Comment (robincornett) [inline includes/api/class-edd-api.php:1608]:
```suggestion
				$discount_list['discounts'][0]['excluded_products']          = edd_get_discount_excluded_products( $discount->ID );
```
(Just adjusting mid-line alignment to use spaces.)

**Review by robincornett — COMMENTED** [review]
This works and I just have reformatting suggestions to apply (mid-line alignment) before final approval.

**Review by robincornett — APPROVED** [review]

**Review by ashleyfae — APPROVED** [review]
