### PR TITLE
Account for Fees of Cart Item Price

### LINKED ISSUE #6859: Cart contents price is incorrect when using fees
# Description:
When you attach a fee in EDD to an item, the $item['price'] is set incorrectly. This causes:
- Order report totals to be wildly incorrect
- Extensions that utilize this feature get the wrong numbers (which if fed into accounting systems or used in tax audit software (to save an independent-of-edd-record) or to back calculate taxes paid (to say generate the taxes to pay to a state)) will be completely wrong

# Instructions (to replicate):
To make this easy, I'm going to use Discounts Pro, but this affects *all EDD Fees* it does not require Discounts Pro.

1. Install Discounts Pro
2. Make a download with a price of $20
3. Give this download a $20 discount in Discounts Pro
4. Hook into edd_payment_saved (picked for simplicity in testing, any hook works, even non-hooks, ie new EDD_Payment also works).
5. Dump $payment_meta = edd_get_payment_meta( $payment_id );
 in this data, $payment_meta['cart_details'] is the cart details, which contains the prices of each product. For each product in the cart details $item['price'] is supposed to contain the "net" (post-tax, post-discount) number for the product ($item['item_price'] contains the pre-number)

Notice, that despite the order being free, and the Fee being directly applied to the product, and the cart details item information having that fee there as -20, it still shows it as $20.

image

Now, repeat this, but instead of using a fee (turn discounts pro off) use a discount code. Note how this adjusted to the correct ($0).

### Information (if a specific version is affected):
I've tested EDD versions between 2.9.4 and 2.6.0. They all seem to have this issue.

This is not a big deal to fix, but it needs to be fixed. And ideally there needs to be a routine that goes through previous orders (we could do this on the 3.0 since we're already migrating them, we could fix them as we insert them), and fixes this.

### PR DESCRIPTION
**Pull request by dancameron**
Fixes #6859

Proposed Changes:
1. Loop through the fees and add them to the total
2. Negative fees will decrease total.

### CODE REVIEW

**Comment by chriscct7** [comment]
This also resolves #4708

File: includes/payments/class-edd-payment.php [hunk 1]
```diff
@@ -1147,7 +1147,16 @@ public function add_download( $download_id = 0, $args = array(), $options = arra
 			$subtotal -= round( $tax, edd_currency_decimal_filter() );
 		}
 
-		$total      = $subtotal - $discount + $tax;
+		$fees = 0;
+		if ( isset( $args['fees'] ) && ! empty( $args['fees'] ) ) {
```
Comment (chriscct7) [inline includes/payments/class-edd-payment.php]: Ideally this should be
`if ( ! empty( $args['fees'] ) && is_array( $args['fees'] ) ) {`

since empty = isset() && !== false, therefore a separate isset isn't needed, though we do need it to be an array to use foreach

Comment (dancameron) [reply includes/payments/class-edd-payment.php]: agreed

**Comment by chriscct7** [comment]
Restarted the travis build because on one of the tests Travis died, but all others completed and passed just fine

**Comment by chriscct7** [comment]
The build is failing because on the  PHP: 5.5 WP_VERSION=4.4.2 WP_MULTISITE=0 combo the Travis verification fails. All other 50+ ones pass. This fail can be ignored.

**Comment by JJJ** [comment]
Tested, and resolves the bug in #6859.

@cklosowski - OK to merge?

**Comment by cklosowski** [comment]
Well crap that was for `master` but the current issue attached is for `release/3.0` it's a long standing bug so we can release it as soon the next EDD Core release is ready and port it to `release/3.0` @JJJ

**Comment by JJJ** [comment]
Yep! I will merge. No problemo!
