### PR TITLE
If no gateways are active, do not show the purchase button by default (filter still runs)

### LINKED ISSUE #7247: White screen when completing a purchase
This happens when no payment method is activated. It may not be a serious problem, but I believe that white screen is not a good way of presenting something that went wrong for a user

There should be a message saying that no method was selected or anything of the sort

### Steps to reproduce the behavior

1.Disable all payment methods
2. Choose a product
3. fill in the form (Personal Info)
4. click 2 or 3x consecutively on the button to finalize the purchase

PHP Version:
PHP 7.2
EDD Version (or branch):
EDD v 2.9.12
WordPress Version:
wp version  5.2
Any other relevant information:

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #7247

Proposed Changes:
1. Wraps the default purchase link button in `edd_checkout_button_purchase` to verify that we have active gateways, to prevent a whitescreen when there are no gateways selected.

### CODE REVIEW

**Comment by cklosowski** [comment]
@SDavisMedia @mintplugins since this affects checkout, I'd like both of you to review and test.

**Comment by cklosowski** [comment]
Actually @SDavisMedia do'nt test, I'll have @pippinsplugins do it.

File: includes/checkout/template.php [hunk 1]
```diff
@@ -972,15 +972,21 @@ function edd_checkout_button_next() {
...
-	$style = edd_get_option( 'button_style', 'button' );
-	$label = edd_get_checkout_button_purchase_label();
+	$enabled_gateways = edd_get_enabled_payment_gateways();
 
 	ob_start();
-?>
-	<input type="submit" class="edd-submit <?php echo $color; ?> <?php echo $style; ?>" id="edd-purchase-button" name="edd-purchase" value="<?php echo $label; ?>"/>
-<?php
+
+	if ( ! empty( $enabled_gateways ) || empty( edd_get_cart_total() ) ) {
```
Comment (pippinsplugins) [inline includes/checkout/template.php]: This will fatal on PHP 5.3 and earlier.

Comment (cklosowski) [reply includes/checkout/template.php]: Yep, fixing, Been writing too much EDD 3.0 code apparently.

**Comment by cklosowski** [comment]
@pippinsplugins fixed the 5.3 compat.
