### PR TITLE
Remove `edd_product_type` for default download

### LINKED ISSUE #7811: 3.0 - Downloads - "0" Values Saving Meta for Download Type
### Expected behavior

When saving a Download with the "Default" product type, no `_edd_product_type` metadata should be saved.

### Actual behavior

`_edd_product_type` saves a `0` value.

### Steps to reproduce the behavior
1) Save a Download with the "Default" product type.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

Introduced in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/8da7e908d7e86920293ffc7c79e4329f3542b8f2

This is breaking things that rely on meta queries using `NOT EXISTS` comparators, such as the Products dropdown excluding Bundles.

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #7811 

Proposed Changes:
1. Search and delete `edd_product_type` field from metadata for "default" products
2. Update meta query to match AJAX search

To Test:
- Create a new default download and check database
- Before database would have `_edd_product_type` of `"0"`
- Now there is no entry for default

### CODE REVIEW

File: includes/admin/downloads/metabox.php [hunk 1]
```diff
@@ -138,16 +136,16 @@ function edd_download_meta_box_save( $post_id, $post ) {
 			}
 
 			update_post_meta( $post_id, $field, $new_default_price_id );
+		} elseif ( '_edd_product_type' === $field && '0' === $_POST[ $field ] ) {
```
Comment (spencerfinnell) [inline includes/admin/downloads/metabox.php:139]: @LisaCee Let's add a comment here explaining that for backwards compatibility no value is stored when Product Type is set to "Default" (represented by a `0` value).

File: includes/class-edd-html-elements.php [hunk 2]
```diff
@@ -86,7 +86,7 @@ public function product_dropdown( $args = array() ) {
 				array(
 					'key'     => '_edd_product_type',
 					'value'   => 'bundle',
-					'compare' => 'NOT EXISTS',
+					'compare' => '!=',
```
Comment (robincornett) [inline includes/class-edd-html-elements.php:89]: The `meta_query` needs to be updated to account both for products which do have the `_edd_product_type` meta key, and for products which no longer have the meta key. This appears to work:

```php
			$product_args['meta_query'] = array(
				'relation' => 'OR',
				array(
					'key'     => '_edd_product_type',
					'value'   => 'bundle',
					'compare' => '!=',
				),
				array(
					'key'     => '_edd_product_type',
					'value'   => 'bundle',
					'compare' => 'NOT EXISTS',
				),
			);
```

Comment (spencerfinnell) [reply includes/class-edd-html-elements.php:89]: @robincornett I believe since this was an unreleased bug and the meta can't exist on `2.9.x` we don't need to account for the times it was saved while testing `3.0`. 

@ashleyfae I know we have some 3.0 database migration routines that are required for those using pre-release 3.0 -- are we also trying to account for temporary data inaccuracies like this?

Comment (ashleyfae) [reply includes/class-edd-html-elements.php:89]: @spencerfinnell Hm introduced in 2018 by the looks of it? That was quite a while ago...

I guess I'm okay with not accounting for it provided that re-saving the download would immediately fix the problem (which I'm guessing it would?).

My preference would be:

1. Don't account for it
2. Write an upgrade routine to fix it

Meta queries are already gross, so I'd rather not build one grosser than it has to be.

Comment (spencerfinnell) [reply includes/class-edd-html-elements.php:89]: @ashleyfae That meta query has been around since then but there hasn't been a possibility to save a value other than `bundle` since `3.0`.  The change by @LisaCee is to provide parity with the AJAX product search that has existed for a while too: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7811#issuecomment-621924359

Comment (robincornett) [reply includes/class-edd-html-elements.php:89]: @spencerfinnell the PR changes the meta query check to `!=` instead of `NOT EXISTS`, so shouldn't that be reverted if we are not checking for both?

Comment (spencerfinnell) [reply includes/class-edd-html-elements.php:89]: @robincornett You're right -- we should update this instance and the other mentioned in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7811#issuecomment-621924359 to check if it is empty, or `!=` bundle. That will ensure Default (no meta) are returned, as well as potential non-`bundle` types (possibly added by extensions).

Sorry for the confusion ☕

**Comment by cklosowski** [comment]
Do we need to do some further fixes based off [this comment](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7816/files#r419454184) concerning using `!=` vs `NOT EXISTS`?

**Comment by LisaCee** [comment]
> Do we need to do some further fixes based off [this comment](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7816/files#r419454184) concerning using `!=` vs `NOT EXISTS`?

I think this is taken care of.  @robincornett , can you confirm ?

**Comment by robincornett** [comment]
I believe the update you made should correct for it--the meta queries now check for any downloads which either do not have the product type meta key at all ( `NOT EXISTS`--preferred default scenario) `OR` do not have it set to `bundle` (`!=`). That second one also leaves room for other "types" of products to be added in the future, if such a thing were desired, so I think the meta query is correct.

**Comment by cklosowski** [comment]
:+1: Thanks @robincornett and @LisaCee
