### PR TITLE
Enqueue the edd-admin-tools-export.js on the upgrade page #6856

### LINKED ISSUE #6856: 3.0: Migration stability (CLI and UI)
### Expected behavior
Using wp edd migrate_payments is expected to successfully migrate all payments.

### Actual behavior
screen shot 2018-08-10 at 9 41 02 pm

The time estimator displays unexpected results, then fails to complete. This is with a site that has 67000 purchase records. Happy to provide more details as needed.

### Information (if a specific version is affected):
PHP Version: 7.0.3

EDD Version (or branch): release/3.0

WordPress Version: 4.9.8

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #6856 

Proposed Changes:
1. Adds the JS for the export tools to allow the AJAX handling of the upgrades
2. Sends in a `$hook` so that we can enqueue the JS for this page only when needed.

### CODE REVIEW

File: includes/scripts.php [hunk 1]
```diff
@@ -300,6 +300,7 @@ function edd_register_admin_scripts() {
 	wp_register_script( 'edd-admin-tax-rates',             $js_dir . 'edd-admin-tax-rates.js',               array( 'wp-backbone', 'jquery-chosen' ), $version, true );
 	wp_register_script( 'edd-admin-email-tags',            $js_dir . 'edd-admin-email-tags.js',              array( 'thickbox', 'wp-util' ), $version );
 	wp_register_script( 'edd-admin-scripts-compatibility', $js_dir . 'edd-admin-backwards-compatibility.js', array( 'jquery', 'edd-admin-scripts' ), $version );
+	wp_register_script( 'edd-admin-tools-export',          $js_dir . 'edd-admin-tools-export.js',            array( 'jquery' ), $version );
```
Comment (spencerfinnell) [inline includes/scripts.php]: This happens automatically below.

Comment (cklosowski) [reply includes/scripts.php]: Oh perfect, i'll go ahead and remove this then.

**Comment by cklosowski** [comment]
fixed that up @spencerfinnell
